apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: observability
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  project: w9-platform
  source:
    repoURL: https://github.com/Remmusss/Remmusss-aws-accelerator-p2.git
    targetRevision: main
    path: cloud/w9/day-b
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
