apiVersion: v1
kind: Pod
metadata:
  name: invalid-missing-resources
  namespace: app-dev
  labels:
    owner: platform-team
    app.kubernetes.io/name: invalid-missing-resources
    app.kubernetes.io/part-of: w10-platform
spec:
  securityContext:
    runAsNonRoot: true
  containers:
    - name: app
      image: nginx:1.27-alpine
      securityContext:
        allowPrivilegeEscalation: false

