apiVersion: v1
kind: Pod
metadata:
  name: invalid-latest-image
  namespace: app-dev
  labels:
    owner: platform-team
    app.kubernetes.io/name: invalid-latest-image
    app.kubernetes.io/part-of: w10-platform
spec:
  securityContext:
    runAsNonRoot: true
  containers:
    - name: app
      image: nginx:latest
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 500m
          memory: 256Mi

