apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
  namespace: observability
data:
  collector.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:

    processors:
      batch:
      memory_limiter:
        check_interval: 1s
        limit_mib: 256
        spike_limit_mib: 64
      resource:
        attributes:
          - key: k8s.cluster.name
            value: w9-lab
            action: upsert

    exporters:
      debug: {}
      prometheus:
        endpoint: 0.0.0.0:8889

    service:
      pipelines:
        metrics:
          receivers: [otlp]
          processors: [memory_limiter, batch, resource]
          exporters: [prometheus, debug]
        logs:
          receivers: [otlp]
          processors: [memory_limiter, batch, resource]
          exporters: [debug]
        traces:
          receivers: [otlp]
          processors: [memory_limiter, batch, resource]
          exporters: [debug]
