apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-collector
  namespace: observability
  labels:
    app: otel-collector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: otel-collector
  template:
    metadata:
      labels:
        app: otel-collector
    spec:
      containers:
        - name: otel-collector
          image: otel/opentelemetry-collector-contrib:0.103.1
          args:
            - --config=/conf/collector.yaml
          ports:
            - containerPort: 4317
              name: otlp-grpc
            - containerPort: 4318
              name: otlp-http
            - containerPort: 8889
              name: prom-export
          volumeMounts:
            - name: collector-config
              mountPath: /conf
          readinessProbe:
            tcpSocket:
              port: otlp-grpc
            initialDelaySeconds: 5
            periodSeconds: 10
      volumes:
        - name: collector-config
          configMap:
            name: otel-collector-config
