apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: w9-root
  namespace: argocd
spec:
  project: w9-platform
  source:
    repoURL: https://github.com/Remmusss/Remmusss-aws-accelerator-p2.git
    targetRevision: main
    path: cloud/w9/day-a/argocd/apps
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
