apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: demo-web
  namespace: observability
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - lab
  selector:
    matchLabels:
      app: demo-web
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
