apiVersion: v1
kind: Namespace
metadata:
  name: platform-system
  labels:
    app.kubernetes.io/part-of: w10-platform
    environment: platform
---
apiVersion: v1
kind: Namespace
metadata:
  name: app-dev
  labels:
    app.kubernetes.io/part-of: w10-platform
    environment: dev
---
apiVersion: v1
kind: Namespace
metadata:
  name: app-prod
  labels:
    app.kubernetes.io/part-of: w10-platform
    environment: prod
---
apiVersion: v1
kind: Namespace
metadata:
  name: security
  labels:
    app.kubernetes.io/part-of: w10-platform
    environment: platform

