apiVersion: v1
kind: ServiceAccount
metadata:
  name: developer-sa
  namespace: app-dev
  labels:
    app.kubernetes.io/name: developer-sa
    app.kubernetes.io/part-of: w10-platform
    owner: platform-team
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: viewer-sa
  namespace: app-dev
  labels:
    app.kubernetes.io/name: viewer-sa
    app.kubernetes.io/part-of: w10-platform
    owner: platform-team
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sre-sa
  namespace: platform-system
  labels:
    app.kubernetes.io/name: sre-sa
    app.kubernetes.io/part-of: w10-platform
    owner: platform-team

