apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-web
  namespace: lab
  labels:
    app: demo-web
    app.kubernetes.io/name: demo-web
    app.kubernetes.io/part-of: w9-platform
spec:
  replicas: 3
  selector:
    matchLabels:
      app: demo-web
  template:
    metadata:
      labels:
        app: demo-web
        app.kubernetes.io/name: demo-web
        app.kubernetes.io/part-of: w9-platform
    spec:
      containers:
        - name: demo-web
          image: demo-web-metrics:local
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
              name: http
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 15
            periodSeconds: 10
