apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: demo-web-prometheus-analysis
  namespace: lab
spec:
  metrics:
    - name: error-rate
      interval: 20s
      count: 3
      failureLimit: 1
      successCondition: result[0] <= 0.05
      failureCondition: result[0] > 0.05
      provider:
        prometheus:
          address: http://kube-prometheus-stack-prometheus.observability.svc.cluster.local:9090
          query: |
            (
              sum(rate(demo_web_http_requests_total{app="demo-web-rollout", status_code=~"5.."}[2m]))
              /
              clamp_min(sum(rate(demo_web_http_requests_total{app="demo-web-rollout"}[2m])), 0.001)
            ) or vector(0)
    - name: p95-latency
      interval: 20s
      count: 3
      failureLimit: 1
      successCondition: result[0] <= 1
      failureCondition: result[0] > 1
      provider:
        prometheus:
          address: http://kube-prometheus-stack-prometheus.observability.svc.cluster.local:9090
          query: |
            histogram_quantile(
              0.95,
              sum by (le) (
                rate(demo_web_http_request_duration_seconds_bucket{app="demo-web-rollout"}[2m])
              )
            ) or vector(0)
