apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: demo-api-secret
  namespace: app-dev
  labels:
    app.kubernetes.io/name: demo-api-secret
    app.kubernetes.io/part-of: w10-platform
    owner: platform-team
spec:
  refreshInterval: 30s
  secretStoreRef:
    name: aws-secretsmanager
    kind: SecretStore
  target:
    name: demo-api-secret
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: /w10/dev/demo-api
        property: username
    - secretKey: password
      remoteRef:
        key: /w10/dev/demo-api
        property: password
    - secretKey: apiKey
      remoteRef:
        key: /w10/dev/demo-api
        property: apiKey
