apiVersion: v1
kind: ServiceAccount
metadata:
  name: eso-reader
  namespace: app-dev
  labels:
    app.kubernetes.io/name: eso-reader
    app.kubernetes.io/part-of: w10-platform
    owner: platform-team
