apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-web
  namespace: lab
spec:
  template:
    metadata:
      labels:
        observability: enabled
    spec:
      containers:
        - name: nginx
          env:
            - name: OTEL_SERVICE_NAME
              value: demo-web
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: service.namespace=lab,deployment.environment=minikube
