apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - manifests/00-namespace.yaml
  - manifests/demo-web-servicemonitor.yaml
  - otel/collector-configmap.yaml
  - otel/collector-deployment.yaml
  - otel/collector-service.yaml
  - alert-rules/demo-web-slo-rules.yaml
