apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - constrainttemplates/required-labels.yaml
  - constrainttemplates/disallow-privileged.yaml
  - constrainttemplates/require-non-root.yaml
  - constrainttemplates/require-resources.yaml
  - constrainttemplates/disallow-latest-tag.yaml
  - constraints/required-labels.yaml
  - constraints/disallow-privileged.yaml
  - constraints/require-non-root.yaml
  - constraints/require-resources.yaml
  - constraints/disallow-latest-tag.yaml

