apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 65.1.1
    helm:
      values: |
        alertmanager:
          config:
            global:
              resolve_timeout: 5m
              smtp_smarthost: smtp.gmail.com:587
              smtp_from: trandinhminhquan207@gmail.com
              smtp_auth_username: trandinhminhquan207@gmail.com
              smtp_auth_password: CHANGE_ME_WITH_GMAIL_APP_PASSWORD
              smtp_require_tls: true
            route:
              receiver: "null"
              group_by:
                - alertname
                - namespace
                - service
              group_wait: 15s
              group_interval: 1m
              repeat_interval: 30m
              routes:
                - receiver: personal-email
                  matchers:
                    - namespace="demo"
                    - alertname=~"Api.*"
            receivers:
              - name: "null"
              - name: personal-email
                email_configs:
                  - to: trandinhminhquan207@gmail.com
                    send_resolved: true
        prometheus:
          prometheusSpec:
            serviceMonitorSelectorNilUsesHelmValues: false
            serviceMonitorNamespaceSelector: {}
            ruleSelectorNilUsesHelmValues: false
            ruleNamespaceSelector: {}
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
